#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WorldOnPalm.Resource", IsApplication=true)]

namespace WorldOnPalm
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int blink = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int brojIgraca = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int brojIgracaDvobojTop = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int brojIgracaTop = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int brojSobeTop = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int brza = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int brza2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bt = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btnotconnected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btSpojeno = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btTop = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cekanjeAdmina = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cekanjeAdminaTop = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int createTop = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int crta = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int crta2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dvoboj = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int dvobojBTTop = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int dvobojBTTop2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int klasicna = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int minus = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int napravi = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int napraviSobuTop = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int nastavi = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int nastavi2 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int NastaviButton = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int netocno = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int NickTop = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int odabirStranaTop = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ploca = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int plus = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Pocetna = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int pokreni = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int pokreni2 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int posljednjaUputa = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int posljednjaUputaDvoboj = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int pridruzise = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int progressBar = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int roundbutton = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int roundbutton2 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int roundbutton3 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int SpajanjeNaBT3Top = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int text = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int tocno = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int verticalBar = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int vlak = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int WorldOnPalm = 2130837550;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060024
			public const int bodovi1 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int bodovi2 = 2131099685;
			
			// aapt resource value: 0x7f060002
			public const int brojIgraca = 2131099650;
			
			// aapt resource value: 0x7f060048
			public const int brojNastavi = 2131099720;
			
			// aapt resource value: 0x7f060005
			public const int brojSobeText = 2131099653;
			
			// aapt resource value: 0x7f060027
			public const int btNastavi = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int btSpajanje = 2131099686;
			
			// aapt resource value: 0x7f060032
			public const int button1 = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int button2 = 2131099699;
			
			// aapt resource value: 0x7f060035
			public const int button3 = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int button4 = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int button5 = 2131099703;
			
			// aapt resource value: 0x7f060039
			public const int button6 = 2131099705;
			
			// aapt resource value: 0x7f060009
			public const int cekanje1 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int cekanje2 = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int cekanjeNaPitanje = 2131099656;
			
			// aapt resource value: 0x7f06002e
			public const int igrac1Tekst = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int igrac2Tekst = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int igrac3Tekst = 2131099696;
			
			// aapt resource value: 0x7f06002c
			public const int igracNaPotezuTekst = 2131099692;
			
			// aapt resource value: 0x7f060001
			public const int igraciMinus = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int igraciNastavi = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int igraciPlus = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060045
			public const int imageView2 = 2131099717;
			
			// aapt resource value: 0x7f06000d
			public const int imeRegijeTekst = 2131099661;
			
			// aapt resource value: 0x7f060019
			public const int imeRegijeTekst2 = 2131099673;
			
			// aapt resource value: 0x7f06000e
			public const int kategorijaPitanjaTekst = 2131099662;
			
			// aapt resource value: 0x7f06001a
			public const int kategorijaPitanjaTekst2 = 2131099674;
			
			// aapt resource value: 0x7f06002b
			public const int napraviButton = 2131099691;
			
			// aapt resource value: 0x7f060031
			public const int napraviSobu = 2131099697;
			
			// aapt resource value: 0x7f060040
			public const int nickButton = 2131099712;
			
			// aapt resource value: 0x7f06003f
			public const int nickText = 2131099711;
			
			// aapt resource value: 0x7f060014
			public const int odgovor1 = 2131099668;
			
			// aapt resource value: 0x7f060020
			public const int odgovor12 = 2131099680;
			
			// aapt resource value: 0x7f060015
			public const int odgovor2 = 2131099669;
			
			// aapt resource value: 0x7f060021
			public const int odgovor22 = 2131099681;
			
			// aapt resource value: 0x7f060016
			public const int odgovor3 = 2131099670;
			
			// aapt resource value: 0x7f060022
			public const int odgovor32 = 2131099682;
			
			// aapt resource value: 0x7f060017
			public const int odgovor4 = 2131099671;
			
			// aapt resource value: 0x7f060023
			public const int odgovor42 = 2131099683;
			
			// aapt resource value: 0x7f060013
			public const int odgovori = 2131099667;
			
			// aapt resource value: 0x7f06001f
			public const int odgovori2 = 2131099679;
			
			// aapt resource value: 0x7f06000f
			public const int pitanje1 = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int pitanje12 = 2131099675;
			
			// aapt resource value: 0x7f060011
			public const int pitanje2 = 2131099665;
			
			// aapt resource value: 0x7f06001d
			public const int pitanje22 = 2131099677;
			
			// aapt resource value: 0x7f060049
			public const int pocetnaButton = 2131099721;
			
			// aapt resource value: 0x7f060029
			public const int pokreniButton = 2131099689;
			
			// aapt resource value: 0x7f06004a
			public const int pokreniIgru = 2131099722;
			
			// aapt resource value: 0x7f06002a
			public const int pridruziSeButton = 2131099690;
			
			// aapt resource value: 0x7f06004b
			public const int progressBar1 = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int progressBar2 = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int progressBar3 = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int progressBar4 = 2131099726;
			
			// aapt resource value: 0x7f06004f
			public const int progressBar5 = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int progressBar6 = 2131099728;
			
			// aapt resource value: 0x7f060007
			public const int provjeriSobu = 2131099655;
			
			// aapt resource value: 0x7f06003b
			public const int seekBar1 = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int seekBar2 = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int seekBar3 = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int seekBar4 = 2131099710;
			
			// aapt resource value: 0x7f060046
			public const int stranaDesno = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int stranaDolje = 2131099719;
			
			// aapt resource value: 0x7f060043
			public const int stranaGore = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int stranaLijevo = 2131099716;
			
			// aapt resource value: 0x7f060010
			public const int tekstPitanja1 = 2131099664;
			
			// aapt resource value: 0x7f06001c
			public const int tekstPitanja12 = 2131099676;
			
			// aapt resource value: 0x7f060012
			public const int tekstPitanja2 = 2131099666;
			
			// aapt resource value: 0x7f06001e
			public const int tekstPitanja22 = 2131099678;
			
			// aapt resource value: 0x7f06002d
			public const int tekstSobe = 2131099693;
			
			// aapt resource value: 0x7f06000c
			public const int textView1 = 2131099660;
			
			// aapt resource value: 0x7f060034
			public const int textView2 = 2131099700;
			
			// aapt resource value: 0x7f060038
			public const int textView3 = 2131099704;
			
			// aapt resource value: 0x7f06003a
			public const int textView4 = 2131099706;
			
			// aapt resource value: 0x7f06000b
			public const int tipPitanja = 2131099659;
			
			// aapt resource value: 0x7f060018
			public const int tipPitanja2 = 2131099672;
			
			// aapt resource value: 0x7f060041
			public const int uputa1 = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int uputa2 = 2131099714;
			
			// aapt resource value: 0x7f060051
			public const int verticalBar = 2131099729;
			
			// aapt resource value: 0x7f060006
			public const int view1 = 2131099654;
			
			// aapt resource value: 0x7f060028
			public const int vrstaIgreView = 2131099688;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int brojIgraca = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int brojIgracaDvoboj = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int brojSobe = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int cekanjeAdmina = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Dvoboj1 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Dvoboj2 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Dvoboj3 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dvobojSpajanjeBT = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int GameTypeManu = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int HostOrJoin = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int KlasicnaIgraLayout1 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int KlasicnaIgraLayout2 = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int KlasicnaIgraLayout3 = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int kreiranjeSobe = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Main = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Nick = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int odabirStrana = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Pocetna = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int posljednjaUputa = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int posljednjaUputaDvoboj = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Rezultati = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Rezultati2 = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Room = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int spajanjeBT = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int spajanjeNaBT2 = 2130903064;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int odabirStranaUputa1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int odabirStranaUputa2 = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
